apiVersion: v1
kind: ReplicationController
metadata:
  name: api-v3
  labels:
    app: api
spec:
  replicas: 1
  selector:
    app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-v3
        image: gcr.io/total-sudoku/sudoku-api:v3
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: 'REDIS_ADDR'
          value: 'redis-master:6379'
