apiVersion: v1
kind: ReplicationController
metadata:
  name: api-v6
  labels:
    app: api-v6
spec:
  replicas: 1
  selector:
    app: api-v6
  template:
    metadata:
      labels:
        app: api-v6
        role: api-frontend
    spec:
      containers:
      - name: api-v6
        image: gcr.io/total-sudoku/sudoku-api:v6
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: 'REDIS_ADDR'
          value: 'redis-master:6379'
